name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@64c0c85d18e984422218383b81c52f8b077404d3 # v1.1.2

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: make install-deps

      - name: Generate JSON Schema
        run: make generate-json-schema

      - name: Release generated artifacts
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: |
            build/**/*.json
